include("${CMAKE_CURRENT_LIST_DIR}/sdl.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/v8.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/nlohmann_json.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/libsodium.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/sqlite3.cmake")