name: Build Nightly

on:
  schedule:
      # run everyday at midnight
    - cron: "0 0 * * *"
  # allow manual running of this job
  workflow_dispatch:

env:
  DATE: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Date
      run: DATE=$(python3 ./.github/tools/getdate.py)

    - name: Build
      run: python3 build.py -a -i
      
    - name: Release Nightly
      id: nightly
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'nightly'
        release_name: 'nightly_${{ env.DATE }}'
        draft: false
        prerelease: false
      
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.nightly.outputs.upload_url }}
        asset_path: ./archives/projectfarm-1.0.45-linux.zip
        asset_name: nightly_linux_${{ env.DATE }}.zip
        asset_content_type: application/zip
      
