name: Build Nightly Linux Docker

on:
  schedule:
      # run everyday at midnight
    - cron: "0 0 * * *"
  # allow manual running of this job
  workflow_dispatch:

jobs:
  build_linux_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Buildx Bake
      uses: docker/bake-action@v1.4.2
      with:
        files: |
          # using a full path here doesn't seem correct
          /home/runner/work/projectfarm/projectfarm/docker/linux-server.yml
      
