name: Build Nightly

on:
  schedule:
      # run everyday at midnight
    - cron: "0 0 * * *"
  # allow manual running of this job
  workflow_dispatch:

env:
  DATE: "date"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Date
      id: date
      run: |
        DATE=$(python3 ./.github/tools/getdate.py)
        echo '::set-output name=DATE::$DATE'

    - name: Echo Date
      run: |
        echo ${{ env.DATE }}
        echo ${{ steps.date.outputs.DATE }}
      
